Repository sthoray/AllRight, pull requests merged in 2020-07, with the labels that each got.

#48 Added code coverage
  .github/workflows/codcov.yml
  README.md
  app/build.gradle
Labels: enhancement

#49 Sort
  .idea/misc.xml
  app/src/main/java/com/sthoray/allright/utils/SortOrder.kt
Labels: enhancement

#51 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#52 Create coverage reports for unittests
  .github/workflows/codcov.yml
  .idea/misc.xml
  app/build.gradle
  build.gradle
Labels: documentation

#56 Search request price
  app/src/main/java/com/sthoray/allright/data/model/search/SearchRequest.kt
Labels: enhancement

#60 Use headers for issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#62 Add bottom navigation bar
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sthoray/allright/data/api/AllGoodsApi.kt
  app/src/main/java/com/sthoray/allright/data/db/AppDatabase.kt
  app/src/main/java/com/sthoray/allright/data/model/browse/TopLevelCategory.kt
  app/src/main/java/com/sthoray/allright/data/repository/AppRepository.kt
  app/src/main/java/com/sthoray/allright/ui/main/fragments/browse/adapter/BrowseAdapter.kt
  app/src/main/java/com/sthoray/allright/ui/main/fragments/browse/view/BrowseFragment.kt
  app/src/main/java/com/sthoray/allright/ui/main/fragments/home/adapter/HomeAdapter.kt
  app/src/main/java/com/sthoray/allright/ui/main/fragments/home/view/HomeFragment.kt
  app/src/main/java/com/sthoray/allright/ui/main/fragments/profile/view/ProfileFragment.kt
  app/src/main/java/com/sthoray/allright/ui/main/view/MainActivity.kt
  app/src/main/java/com/sthoray/allright/ui/main/viewmodel/MainViewModel.kt
  app/src/main/res/drawable/ic_browse_24dp.xml
  app/src/main/res/drawable/ic_home_24dp.xml
  app/src/main/res/drawable/ic_profile_24dp.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_browse.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/item_layout_featured_category.xml
  app/src/main/res/layout/item_layout_top_level_category.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement, experimental

#68 Rewrite Room database to enable a local search history #67
  app/src/main/java/com/sthoray/allright/data/api/AllGoodsApi.kt
  app/src/main/java/com/sthoray/allright/data/db/Converters.kt
  app/src/main/java/com/sthoray/allright/data/db/ListingDao.kt
  app/src/main/java/com/sthoray/allright/data/db/SearchHistoryDao.kt
  app/src/main/java/com/sthoray/allright/data/db/SearchHistoryDatabase.kt
  app/src/main/java/com/sthoray/allright/data/db/SearchRequestConverters.kt
  app/src/main/java/com/sthoray/allright/data/model/search/Listing.kt
  app/src/main/java/com/sthoray/allright/data/model/search/Location.kt
  app/src/main/java/com/sthoray/allright/data/model/search/PropertyFilter.kt
  app/src/main/java/com/sthoray/allright/data/model/search/SearchRequest.kt
  app/src/main/java/com/sthoray/allright/data/repository/AppRepository.kt
  app/src/main/java/com/sthoray/allright/ui/main/view/MainActivity.kt
  app/src/main/java/com/sthoray/allright/ui/search/view/SearchActivity.kt
Labels: bug, enhancement

#72 Issue41 shared models
  app/src/main/java/com/sthoray/allright/data/api/AllGoodsApi.kt
  app/src/main/java/com/sthoray/allright/data/model/browse/TopLevelCategory.kt
  app/src/main/java/com/sthoray/allright/data/model/listing/Category.kt
  app/src/main/java/com/sthoray/allright/data/model/listing/Image.kt
  app/src/main/java/com/sthoray/allright/data/model/listing/Listing.kt
  app/src/main/java/com/sthoray/allright/data/model/listing/ListingCategory.kt
  app/src/main/java/com/sthoray/allright/data/model/listing/ListingImage.kt
  app/src/main/java/com/sthoray/allright/data/model/listing/ListingMainImage.kt
  app/src/main/java/com/sthoray/allright/data/model/listing/ListingManager.kt
  app/src/main/java/com/sthoray/allright/data/model/listing/ListingPickupLocation.kt
  app/src/main/java/com/sthoray/allright/data/model/listing/ListingRelated.kt
  app/src/main/java/com/sthoray/allright/data/model/listing/ListingStats.kt
  app/src/main/java/com/sthoray/allright/data/model/listing/Manager.kt
  app/src/main/java/com/sthoray/allright/data/model/listing/MarkdownOptions.kt
  app/src/main/java/com/sthoray/allright/data/model/listing/PickupLocation.kt
  app/src/main/java/com/sthoray/allright/data/model/listing/ShippingOption.kt
  app/src/main/java/com/sthoray/allright/data/model/listing/StoreRelated.kt
  app/src/main/java/com/sthoray/allright/data/model/main/FeatureCategoriesResponse.kt
  app/src/main/java/com/sthoray/allright/data/model/main/FeatureCategory.kt
  app/src/main/java/com/sthoray/allright/data/model/search/Listing.kt
  app/src/main/java/com/sthoray/allright/data/model/search/MainImage.kt
  app/src/main/java/com/sthoray/allright/data/model/search/SearchResponse.kt
  app/src/main/java/com/sthoray/allright/data/model/search/ShippingOption.kt
  app/src/main/java/com/sthoray/allright/ui/main/fragments/browse/adapter/BrowseAdapter.kt
  app/src/main/java/com/sthoray/allright/ui/main/fragments/home/adapter/HomeAdapter.kt
  app/src/main/java/com/sthoray/allright/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/sthoray/allright/ui/search/adapter/ResultsAdapter.kt
  build.gradle
Labels: bug, enhancement

#75 Internet checking
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sthoray/allright/ui/base/ViewModelProviderFactory.kt
  app/src/main/java/com/sthoray/allright/ui/main/fragments/home/view/HomeFragment.kt
  app/src/main/java/com/sthoray/allright/ui/main/view/MainActivity.kt
  app/src/main/java/com/sthoray/allright/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/sthoray/allright/ui/search/view/ResultsFragment.kt
  app/src/main/java/com/sthoray/allright/ui/search/view/SearchActivity.kt
  app/src/main/java/com/sthoray/allright/ui/search/viewmodel/SearchViewModel.kt
  app/src/main/java/com/sthoray/allright/utils/Internet.kt
Labels: bug, enhancement

#74 Add search filtering fragment
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sthoray/allright/ui/main/fragments/browse/view/BrowseFragment.kt
  app/src/main/java/com/sthoray/allright/ui/main/fragments/home/view/HomeFragment.kt
  app/src/main/java/com/sthoray/allright/ui/search/adapter/ResultsAdapter.kt
  app/src/main/java/com/sthoray/allright/ui/search/view/FiltersFragment.kt
  app/src/main/java/com/sthoray/allright/ui/search/view/ResultsFragment.kt
  app/src/main/java/com/sthoray/allright/ui/search/viewmodel/SearchViewModel.kt
  app/src/main/java/com/sthoray/allright/utils/SortOrder.kt
  app/src/main/res/drawable/ic_filter_24.xml
  app/src/main/res/layout/fragment_filters.xml
  app/src/main/res/layout/fragment_results.xml
  app/src/main/res/navigation/search_navigation.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: enhancement
