Repository sthoray/AllRight, pull requests merged in 2020-05, with the labels that each got.

#18 Splash Screen
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sthoray/allright/MainActivity.kt
  app/src/main/java/com/sthoray/allright/SplashScreenActivity.kt
  app/src/main/res/drawable/allrightlogo.png
  app/src/main/res/drawable/categoryicon.png
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/layout/topcategory_row.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#17 Docs
  .github/workflows/android-master.yml
  .gitignore
  README.md
  app/build.gradle
  app/src/main/java/com/sthoray/allright/MainActivity.kt
  app/src/main/java/com/sthoray/allright/TopLevelAdapter.kt
  build.gradle
  docs/dokka/app/alltypes/index.html
  docs/dokka/app/com.sthoray.allright/-main-activity/-init-.html
  docs/dokka/app/com.sthoray.allright/-main-activity/fetch-json.html
  docs/dokka/app/com.sthoray.allright/-main-activity/index.html
  docs/dokka/app/com.sthoray.allright/-main-activity/on-create.html
  docs/dokka/app/com.sthoray.allright/-top-level-adapter/-init-.html
  docs/dokka/app/com.sthoray.allright/-top-level-adapter/get-item-count.html
  docs/dokka/app/com.sthoray.allright/-top-level-adapter/index.html
  docs/dokka/app/com.sthoray.allright/-top-level-adapter/on-bind-view-holder.html
  docs/dokka/app/com.sthoray.allright/-top-level-adapter/on-create-view-holder.html
  docs/dokka/app/com.sthoray.allright/-top-level-adapter/top-level.html
  docs/dokka/app/com.sthoray.allright/-top-level-category/-init-.html
  docs/dokka/app/com.sthoray.allright/-top-level-category/icon.html
  docs/dokka/app/com.sthoray.allright/-top-level-category/id.html
  docs/dokka/app/com.sthoray.allright/-top-level-category/index.html
  docs/dokka/app/com.sthoray.allright/-top-level-category/listing_count.html
  docs/dokka/app/com.sthoray.allright/-top-level-category/name.html
  docs/dokka/app/com.sthoray.allright/-top-level-view-holder/-init-.html
  docs/dokka/app/com.sthoray.allright/-top-level-view-holder/index.html
  docs/dokka/app/com.sthoray.allright/-top-level-view-holder/view.html
  docs/dokka/app/com.sthoray.allright/index.html
  docs/dokka/app/index-outline.html
  docs/dokka/app/index.html
  docs/dokka/app/package-list
  docs/dokka/style.css
Labels: documentation

#19 Patch OkHttp lib version
  app/build.gradle
  app/src/main/java/com/sthoray/allright/MainActivity.kt
Labels: bug

#20 Search functionality
  app/build.gradle
  app/src/main/java/com/sthoray/allright/APIExamples.kt
  app/src/main/java/com/sthoray/allright/MainActivity.kt
  app/src/main/java/com/sthoray/allright/Models.kt
  app/src/main/java/com/sthoray/allright/SearchModels.kt
  docs/dokka/app/alltypes/index.html
  docs/dokka/app/com.sthoray.allright/-top-level-category/-init-.html
  docs/dokka/app/com.sthoray.allright/-top-level-category/icon.html
  docs/dokka/app/com.sthoray.allright/-top-level-category/id.html
  docs/dokka/app/com.sthoray.allright/-top-level-category/index.html
  docs/dokka/app/com.sthoray.allright/-top-level-category/listing_count.html
  docs/dokka/app/com.sthoray.allright/-top-level-category/name.html
  docs/dokka/app/com.sthoray.allright/index.html
  docs/dokka/app/index-outline.html
Labels: enhancement

#23 App Resources
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/sthoray/allright/APIExamples.kt
  app/src/main/java/com/sthoray/allright/ExploreActivity.kt
  app/src/main/java/com/sthoray/allright/SearchActivity.kt
  app/src/main/java/com/sthoray/allright/SplashScreenActivity.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/allrightlogo.png
  app/src/main/res/drawable/categoryicon.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/layout/featured_category_row.xml
  app/src/main/res/layout/top_level_row.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: enhancement

#25 Search activity v2
  app/src/main/java/com/sthoray/allright/SearchActivity.kt
Labels: enhancement
